### PR TITLE
Add a public initializer for ErrorResult

### PR DESCRIPTION
**Pull request by jfperusse**
This allows for external users to return failure reponses.

### CODE REVIEW

**Review by codeface-io — APPROVED** [review]
Thanks for spotting that! The tests don't catch it because they use `@testable` with the import. If you want, you may add a test case file that does explicitly not use `@testable` and can thereby test the availability of public API ...

**Comment by codeface-io** [comment]
Ok, no worries, I just added the test file. And your change is now available as version 0.3.17. Enjoy ☺️

**Comment by jfperusse** [comment]
> Ok, no worries, I just added the test file. And your change is now available as version 0.3.17. Enjoy ☺️

Thanks a lot for the quick reply and merge! I am adding the public tests as well :)

**Comment by jfperusse** [comment]
> > Ok, no worries, I just added the test file. And your change is now available as version 0.3.17. Enjoy ☺️
> 
> Thanks a lot for the quick reply and merge! I am adding the public tests as well :)

Oh, wait, you did :D Thank you!

**Pull request merged**
